name: Update and Deploy Lambda
run-name: ${{ github.actor }} is running an action to update and deploy the lambda
on:
  push:
    branches: [main]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: npm Install
        run: npm install

      - name: Tests
        run: npm test

      - name: Create artifact
        run: zip -r function.zip .
      
      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
          TF_VAR_tf_state_key: ${{ secrets.BUCKET_KEY }}
        run: terraform -chdir=terraform plan